export default {
"00" : "Place",
"03" : "City and Borough",
"04" : "Borough",
"05" : "Census Area",
"06" : "County",
"07" : "District",
"10" : "Island",
"12" : "Municipality",
"13" : "Municipio",
"15" : "Parish",
"20" : "barrio",
"21" : "borough",
"22" : "census county division",
"23" : "census subarea",
"24" : "census subdistrict",
"25" : "city",
"26" : "county",
"27" : "district",
// "28" : "District (prefix)",
// "29" : "precinct",
// "30" : "Precinct (prefix)",
"31" : "gore",
"32" : "grant",
"36" : "location",
"37" : "municipality",
"39" : "plantation",
"41" : "barrio-pueblo",
"42" : "purchase",
"43" : "town",
"44" : "township",
// "45" : "Township (prefix)",
"46" : "UT",
"47" : "village",
"49" : "charter township",
"51" : "subbarrio",
"53" : "city and borough",
"55" : "comunidad",
"57" : "census-designated place",
"62" : "zona urbana",
"68" : "Region",
"69" : "Division",
// "70" : "UGA",
// "71" : "CMSA",
// "72" : "MSA",
"73" : "Primary Metropolitan Statistical Area",
"74" : "New England County Metropolitan Area",
"75" : "Urbanized Area",
"76" : "Urban Cluster",
"77" : "Alaska Native Regional Corporation",
"78" : "Hawaiian Home Land",
// "79" : "ANVSA",
// "80" : "TDSA",
"81" : "Colony",
"82" : "Community",
"83" : "joint-use area",
"84" : "Pueblo",
"85" : "Rancheria",
"86" : "Reservation",
"87" : "Reserve",
// "88" : "OTSA",
"89" : "Trust Land",
// "90" : "joint-use OTSA",
"91" : "Ranch",
// "92" : "SDTSA",
"93" : "Indian Village",
"94" : "Village",
"95" : "Indian Community",
"96" : "Indian Reservation",
"97" : "Indian Rancheria",
"98" : "Indian Colony",
"99" : "Pueblo de",
"9C" : "Pueblo of",
"9D" : "Ranch Reservation",
"9E" : "Rancheria Reservation",
"9F" : "Ranches",
// "B1" : "Balance of County",
// "B2" : "Balance of Parish",
// "B3" : "Balance of Borough",
// "B4" : "Balance of Census Area",
"B5" : "town",
"B6" : "township",
"B7" : "charter township",
// "B8" : "Balance of",
// "BG" : "Block Group (prefix)",
// "BI" : "Balance of Island",
// "BK" : "Block (prefix)",
// "BL" : "(balance)",
// "C1" : "Congressional District (at Large) (actual text)",
// "C2" : "Congressional District (prefix)",
// "C3" : "Resident Commissioner District (at Large) (actual text)",
// "C4" : "Delegate District (at Large) (actual text)",
// "C5" : "No Representative (actual text)",
"CB" : "consolidated government",
"CG" : "consolidated government",
"CN" : "corporation",
"CR" : "Commercial Region",
// "CT" : "Census Tract (prefix)",
// "IB" : "Tribal Block Group (prefix)",
// "IT" : "Tribal Census Tract (prefix)",
// "L1" : "Ward (prefix)",
"L2" : "Senatorial District",
// "L3" : "Assembly District (prefix)",
// "L4" : "General Assembly District (prefix)",
// "L5" : "State Legislative District (prefix)",
// "L6" : "State Legislative Subdistrict (prefix)",
"L7" : "District",
// "LL" : "State House District (prefix)",
// "LU" : "State Senate District (prefix)",
"M0" : "CSA",
"M1" : "Metro Area",
"M2" : "Micro Area",
"M3" : "Metro Division",
"M4" : "Combined NECTA",
"M5" : "Metropolitan NECTA",
"M6" : "Micropolitan NECTA",
"M7" : "NECTA Division",
"MB" : "metropolitan government",
"MG" : "metropolitan government",
"MT" : "metro government",
// "P1" : "SuperPUMA (prefix)",
// "P5" : "PUMA (prefix)",
"T1" : "Area",
"T2" : "Chapter",
"T3" : "Segment",
"TA" : "Administrative Area",
"TB" : "Addition",
// "TC" : "County District (prefix)",
// "TZ" : "TAZ (prefix)",
"UB" : "unified government",
"UC" : "urban county",
"UG" : "unified government",
// "V1" : "Voting District (prefix)",
"V2" : "Voting District",
"Z3" : "ZCTA3",
"Z5" : "ZCTA5"
}
